# ===============================
# = SERVER
# ===============================
server:
  port: 8080
  shutdown: graceful

# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: gaia-meta-service
    zipkin:
      enabled: false
      base-url: http://127.0.0.1:9411
    sleuth:
      enabled: true
      sampler:
        probability: 1.0

  datasource:
    # 개선 커넥션 풀 db사용
    url: jdbc:mysql://localhost:3306/scott?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiger
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10

  jpa:
    generate-ddl: true
    hibernate:
      # create / create-drop / update / validate / none
      ddl_auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
        format_sql: true
        default_batch_fetch_size: 1000
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        javax:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE
#      connection:
#        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/scott?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: tiger
#    jpa:
#      hibernate:
#        naming:
#          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        # create / create-drop / update / validate / none
#        ddl-auto: create-drop
#        use-new-id-generator-mappings: true
#        default_batch_fetch_size: 1000
#        cache:
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#        javax:
#          persistence:
#            sharedCache:
#              mode: ENABLE_SELECTIVE
#      show-sql: true


#########################################################
#### Eureka
#########################################################
#eureka:
#  instance:
#  #    hostname: ${spring.application.name}
#  #    prefer-ip-address: true
#  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${spring.cloud.hostname}
#  #instance-id: ${spring.cloud.hostname}:${spring.application.name}:${spring.application.instance_id}:${server.port}
#  server:
#    response-cache-update-interval-ms: 3000 # Response 캐싱 주기
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 3 # 서비스 목록 3초마다 캐싱
#    disable-delta: true #캐싱할 때 변경된 부분만 업데이트

#########################################################
#### Actuator
#########################################################
management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health: _check
  endpoint:
    health:
      show-details: never

#########################################################
#### logging
#########################################################
logging:
  level:
    root: INFO
    tving.gaia: DEBUG
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    #org.springframework.cloud.sleuth: TRACE
    org.springframework.cache: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.jpa: TRACE
    #org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG


#########################################################
#### CUSTOM PROPERTIES
#########################################################
IMAGE_SERVER: http://image-dev.tving.com